-   id: djangOK
    name: djangOK
    description: Make sure that django can start
    entry: python manage.py check --deploy
    language: system
    types: []
    always_run: true
    fail_fast: true
    pass_filenames: false
    args: []
-   id: django_migrations
    name: django Migrations 👍
    description: Make sure that django migrations is OK
    entry: python manage.py migrate --fake
    language: system
    types: []
    always_run: true
    fail_fast: true
    pass_filenames: false
    args: []
