-   id: djangOK
    name: djangOK
    description: Make sure that django can start
    entry: python manage.py check --deploy
    language: system
    types: []
    always_run: true
    fail_fast: true
    pass_filenames: false
    args: []
